/* eslint-disable @next/next/no-img-element */
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Styles from "../styles/Home.module.css"


export default function Home() {
  const [products, setProducts] = useState([])
  const [error,setError] = useState(false)

  useEffect(()=>{
      const fetchProducts = async () => {
          try {
            const response = await axios('https://api.tjori.com/api/v7filters/na/women-all-products/?f_page=1&format=json');
            if(response.status===200){
              console.log(response.data.data.products);
                setProducts(response.data.data.products)
            }

          } catch (error) {
              setError(error.response.data)
          }
      }
      fetchProducts()
  },[])

  return (
    
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={Styles.productContainerGrid}>
           {/* products lists */}
            {
                products.map((product,index)=>{
                  return (
                    <div key={index} className="product-card">
                          <div>
                            <img src={product.plpimaage} alt="product-img" 
                            className="productImg" 
                            />
                          </div>
                          <div className="title">
                            <h3>{product.name}</h3>
                          </div>
                          <div className="div">
                            <p>{product.price}</p>
                          </div>
                    </div>   
                  )
                })
            }
        </div>
    </div> 
  )
}
